export const foods = [
  {
    name: "Creamy Coconut Curry Rice With Vegetables",
    category: "chicken",
    src: "https://www.walderwellness.com/creamy-coconut-curry-rice-with-vegetables/",
    title: "Walder Wellness",
    ingredients: [
      {qty: "400ml", ingredient: "coconut milk"},
      {qty: "1 cup", ingredient: "(brown) rice"},
      {qty: "1 cup", ingredient: "water"},
      {qty: "1 tbsp", ingredient: "curry powder"},
      {qty: "3 cups", ingredient: "vegetables"},
      {qty: "1 clove", ingredient: "garlic"},
      {qty: "", ingredient: "salt"},
      {qty: "", ingredient: "pepper"},
      {qty: "", ingredient: "olive oil"},
    ],
    instructions:
      "This coconut curry rice is made with creamy coconut milk and packed with vegetables like broccoli, zucchini, mushrooms, and peppers.",
    long_instructions: [
      "1. Rinse brown rice in a sieve then transfer to a large pot.",
      "2. Add water, 3/4 cup coconut milk, curry powder, salt, and pepper to the pot with the rice. Stir, then bring to a boil over high heat.",
      "3. Once the liquid starts to boil, cover and reduce to low heat. Allow to simmer for about 40 minutes. **NOTE: all rice brands are a bit different, so please check the packaging of the rice you're using to see the exact amount of liquid to rice ratio and cooking time. See recipes notes for more tips!",
      "4. Heat olive oil in a large pan over medium-high. Cook shallots and garlic for a few minutes, until lightly browned and fragrant.",
      "5. Then, add all the chopped vegetables to the pan and cook until they're tender and lightly browned (about 10-12 minutes), stirring frequently.",
      "6. Once the rice is cooked, stir in all the cooked vegetables and the remainder of the coconut milk. Adjust seasonings to taste. TIP: If you'd like the coconut milk to absorb a bit more, simply continue to cook for a minute or two while stirring everything together.",
      "7. Serve with your favourite protein and enjoy hot!",
    ],
  },
  {
    name: "Pumpkin Curry Soup",
    category: "soup",
    src: "https://themodernproper.com/curried-pumpkin-coconut-soup",
    title: "the modern proper",
    ingredients: [
      {qty: "2.5 lbs", ingredient: "sugar pumpkin"},
      {qty: "1.5 lbs", ingredient: "butternut squash"},
      {qty: "0.5 cup", ingredient: "coconut milk"},
      {qty: "6 cups", ingredient: "vegetable stock"},
      {qty: "2 clove", ingredient: "onion"},
      {qty: "", ingredient: "garlic"},
      {qty: "1 tsp", ingredient: "curry powder"},
      {qty: "", ingredient: "nutmeg"},
      {qty: "", ingredient: "salt"},
      {qty: "", ingredient: "pepper"},
      {qty: "", ingredient: "olive oil"},
    ],
    instructions:
      "Velvety smooth and brilliantly hued, this creamy vegan pumpkin curry soup recipe is deeply beloved in our homes.",
    long_instructions: [
      "1. Prepare the pumpkin and butternut squash, if you have a sharp peeler, it actually works quite well to use it to remove the skins from the squash. Cube the pumpkin and squash flesh into 2-3” chunks.",
      "2. Heat the oil in a large dutch oven or heavy soup pot, sauté onions until translucent, about 5 minutes. Add garlic and sauté for 2 more minutes.",
      "3. Add the pumpkin, squash, curry, nutmeg, ginger, red pepper, salt and pepper and stock. Stir and bring to a boil. Reduce to a simmer and cook until squash is tender and can be pierced with a fork, about 15-20 minutes.",
      "4. Puree the soup in a food processor or blender in small batches.",
      "5. Once your soup is nice and creamy return it to the pot. Add your coconut milk, additional salt and pepper if needed and warm it back up over medium heat.",
      "6. Serve with pumpkin seeds, a swirl of extra coconut milk, sliced jalapenos and a little cilantro. Enjoy!",
    ],
  },
  {
    name: "Chickpea, Avocado, & Feta Salad",
    category: "salad",
    src: "https://www.twopeasandtheirpod.com/chickpea-avocado-feta-salad/",
    title: "two peas & their pod",
    ingredients: [
      {qty: "1 can", ingredient: "chickpeas"},
      {qty: "2", ingredient: "avocados"},
      {qty: "0.5 cup", ingredient: "cilantro"},
      {qty: "0.5 cup", ingredient: " feta cheese"},
      {qty: "1", ingredient: "lime"},
      {qty: "", ingredient: "salt"},
      {qty: "", ingredient: "pepper"},
    ],
    instructions:
      "Velvety smooth and brilliantly hued, this creamy vegan pumpkin curry soup recipe is deeply beloved in our homes.",
    long_instructions: [
      "1. Prepare the pumpkin and butternut squash, if you have a sharp peeler, it actually works quite well to use it to remove the skins from the squash. Cube the pumpkin and squash flesh into 2-3” chunks.",
      "2. Heat the oil in a large dutch oven or heavy soup pot, sauté onions until translucent, about 5 minutes. Add garlic and sauté for 2 more minutes.",
      "3. Add the pumpkin, squash, curry, nutmeg, ginger, red pepper, salt and pepper and stock. Stir and bring to a boil. Reduce to a simmer and cook until squash is tender and can be pierced with a fork, about 15-20 minutes.",
      "4. Puree the soup in a food processor or blender in small batches.",
      "5. Once your soup is nice and creamy return it to the pot. Add your coconut milk, additional salt and pepper if needed and warm it back up over medium heat.",
      "6. Serve with pumpkin seeds, a swirl of extra coconut milk, sliced jalapenos and a little cilantro. Enjoy!",
    ],
  },
  {
    name: "Spiced carrot & lentil soup",
    category: "soup",
    src: "https://www.bbcgoodfood.com/recipes/spiced-carrot-lentil-soup",
    title: "BBC good food",
    ingredients: [
      {qty: "2 tsp", ingredient: "cumin seeds"},
      {qty: "600 g", ingredient: "carrots"},
      {qty: "140 g", ingredient: "split red lentils"},
      {qty: "125 ml", ingredient: "milk"},
      {qty: "2 tbs", ingredient: "olive oil"},
      {qty: "", ingredient: "chilli flakes"},
      {qty: "", ingredient: "salt"},
      {qty: "", ingredient: "pepper"},
    ],
    instructions:
      "A delicious, spicy blend packed full of iron and low in fat to boot.",
    long_instructions: [],
  },
  {
    name: "Chicken & sweetcorn tacos",
    category: "chicken",
    src: "https://www.bbcgoodfood.com/recipes/chicken-sweetcorn-tacos",
    title: "BBC good food",
    ingredients: [
      {qty: "250 g", ingredient: "flour"},
      {qty: "5", ingredient: "chicken breast"},
      {qty: "0.2", ingredient: "red cabbage"},
      {qty: "3", ingredient: "limes"},
      {qty: "400 g", ingredient: "corn"},
      {qty: "", ingredient: "garlic"},
      {qty: "", ingredient: "salt"},
      {qty: "", ingredient: "pepper"},
      {qty: "", ingredient: "olive oil"},
    ],
    instructions:
      "Serve up these healthy chicken and sweetcorn tacos for an easy midweek meal that's full of flavour. You'll also have leftovers to make chicken and sweetcorn wraps for lunch tomorrow",
    long_instructions: [],
  },
  {
    name: "Ricotta, broccoli & new potato frittata",
    category: "herbs",
    src: "https://www.bbcgoodfood.com/recipes/ricotta-broccoli-new-potato-frittata",
    title: "BBC good food",
    ingredients: [
      {qty: "100 g", ingredient: "(new) potatoes"},
      {qty: "200 g", ingredient: "broccoli"},
      {qty: "200 g", ingredient: "green beans"},
      {qty: "400 g", ingredient: "mixed beans"},
      {qty: "4", ingredient: "eggs"},
      {qty: "50 g", ingredient: "ricotta"},
      {qty: "", ingredient: "basil"},
      {qty: "", ingredient: "salt"},
      {qty: "", ingredient: "pepper"},
      {qty: "", ingredient: "olive oil"},
    ],
    instructions:
      "Make this quick and healthy frittata with a bean salad in 30 minutes flat. Flavoured with broccoli and ricotta.",
    long_instructions: [],
  },
  {
    name: "Chicken with crushed harissa chickpeas",
    category: "chicken",
    src: "https://www.bbcgoodfood.com/recipes/chicken-crushed-harissa-chickpeas",
    title: "BBC good food",
    ingredients: [
      {qty: "4", ingredient: "chicken breast"},
      {qty: "1", ingredient: "yellow pepper"},
      {qty: "400 g", ingredient: "chickpeas"},
      {qty: "1.5 tbs", ingredient: "red harissa paste"},
      {qty: "150 g", ingredient: "baby spinach"},
      {qty: "", ingredient: "parsley"},
      {qty: "", ingredient: "salt"},
      {qty: "", ingredient: "pepper"},
      {qty: "", ingredient: "olive oil"},
    ],
    instructions:
      "Need something speedy for dinner? Try this chicken, coated in flavourful za'atar and served with spiced chickpeas.",
    long_instructions: [],
  },
  {
    name: "Pesto chicken salad",
    category: "chicken",
    src: "https://www.bbcgoodfood.com/recipes/pesto-chicken-salad",
    title: "BBC good food",
    ingredients: [
      {qty: "50 g", ingredient: "couscous"},
      {qty: "2 tbs", ingredient: "pesto"},
      {qty: "2 tbs", ingredient: "(greek) yogurt"},
      {qty: "2", ingredient: "chicken breast"},
      {qty: "0.5", ingredient: "cucumber"},
      {qty: "", ingredient: "lettuce"},
      {qty: "2 tbs", ingredient: "toasted pine nuts"},
      {qty: "2", ingredient: "sundried tomatoes"},
      {qty: "", ingredient: "basil"},
      {qty: "", ingredient: "salt"},
      {qty: "", ingredient: "pepper"},
      {qty: "", ingredient: "olive oil"},
    ],
    instructions:
      "Serve this pesto chicken and couscous salad in lettuce leaves for a healthy supper. With added sundried tomatoes and pine nuts, it has lots of texture.",
    long_instructions: [],
  },
  {
    name: "Pesto chicken salad",
    category: "chicken",
    src: "https://www.bbcgoodfood.com/recipes/pesto-chicken-salad",
    title: "BBC good food",
    ingredients: [{qty: "50 g", ingredient: "couscous"}],
    instructions: "Serve this pesto chicken and couscous",
    long_instructions: [],
  },
];
export const allUsers = [
  {user_name: "Teodora", selected_foods: []},
  {user_name: "Erik", selected_foods: []},
  {user_name: "Toamna", selected_foods: []},
  {user_name: "Hesi", selected_foods: []},
];
